// Game content extracted from The Barons v3 print & play cutouts.
// All payouts are per invested $100.

export const PROJECTS = [
  {
    id: 'municipal_utilities_network',
    name: 'Municipal Utilities Network',
    class: 'Defensive',
    table: [
      { min: 2, max: 4, payout: -100 },
      { min: 5, max: 7, payout: 0 },
      { min: 8, max: 9, payout: 100 },
      { min: 10, max: 11, payout: 200 },
      { min: 12, max: 12, payout: 300 },
    ],
    bonusKey: 'municipal_idio_cap',
    bonusText: 'Idiosyncratic negative modifiers are only -$100.',
  },
  {
    id: 'food_processing_consortium',
    name: 'Food Processing Consortium',
    class: 'Defensive',
    table: [
      { min: 2, max: 3, payout: -200 },
      { min: 4, max: 6, payout: 0 },
      { min: 7, max: 8, payout: 100 },
      { min: 9, max: 10, payout: 200 },
      { min: 11, max: 12, payout: 400 },
    ],
    bonusKey: 'food_processing_macro_benefits',
    bonusText: 'Receive payout benefits from Military and Growth oriented Macro Regimes.',
  },
  {
    id: 'government_bond_syndicate',
    name: 'Government Bond Syndicate',
    class: 'Defensive',
    table: [
      { min: 2, max: 5, payout: 100 },
      { min: 6, max: 9, payout: 200 },
      { min: 10, max: 12, payout: 200 },
    ],
    bonusKey: 'gov_bond_floor_no_contagion',
    bonusText: 'Cannot drop below $0 if no Systemic Contagion.',
  },
  {
    id: 'national_railroad_expansion',
    name: 'National Railroad Expansion',
    class: 'Normal',
    table: [
      { min: 2, max: 3, payout: -300 },
      { min: 4, max: 6, payout: -100 },
      { min: 7, max: 8, payout: 100 },
      { min: 9, max: 10, payout: 300 },
      { min: 11, max: 12, payout: 500 },
    ],
    bonusKey: 'railroad_monopoly_full',
    bonusText: 'Collect all the benefits of the Monopoly Amplifier, not half.',
  },
  {
    id: 'commercial_banking_expansion',
    name: 'Commercial Banking Expansion',
    class: 'Normal',
    table: [
      { min: 2, max: 3, payout: -300 },
      { min: 4, max: 5, payout: -100 },
      { min: 6, max: 8, payout: 300 },
      { min: 9, max: 10, payout: 200 },
      { min: 11, max: 12, payout: 0 },
    ],
    bonusKey: 'banking_three_positive',
    bonusText: 'If 3 Projects are positive this round, +$200.',
  },
  {
    id: 'distillery',
    name: 'Distillery',
    class: 'Normal',
    table: [
      { min: 2, max: 3, payout: 400 },
      { min: 4, max: 5, payout: 300 },
      { min: 6, max: 7, payout: 200 },
      { min: 8, max: 9, payout: 100 },
      { min: 10, max: 11, payout: 0 },
      { min: 12, max: 12, payout: -100 },
    ],
    bonusKey: 'distillery_three_negative',
    bonusText: 'If 3 Projects are negative this round, +$200.',
  },
  {
    id: 'steel_foundry_modernization',
    name: 'Steel Foundry Modernization',
    class: 'Growth',
    table: [
      { min: 2, max: 3, payout: -400 },
      { min: 4, max: 6, payout: -200 },
      { min: 7, max: 8, payout: 100 },
      { min: 9, max: 10, payout: 400 },
      { min: 11, max: 12, payout: 700 },
    ],
    bonusKey: 'steel_ignore_negative_cross',
    bonusText: 'Ignore negative Cross-Project adjustments.',
  },
  {
    id: 'electrical_grid_innovation',
    name: 'Electrical Grid Innovation',
    class: 'Growth',
    table: [
      { min: 2, max: 4, payout: -500 },
      { min: 5, max: 7, payout: 0 },
      { min: 8, max: 9, payout: 200 },
      { min: 10, max: 12, payout: 600 },
    ],
    bonusKey: 'grid_normal_macro_plus_100',
    bonusText: 'In a Normal Macro Regime, +$100.',
  },
  {
    id: 'transcontinental_shipping_line',
    name: 'Transcontinental Shipping Line',
    class: 'Growth',
    table: [
      { min: 2, max: 4, payout: -300 },
      { min: 5, max: 6, payout: -100 },
      { min: 7, max: 8, payout: 200 },
      { min: 9, max: 10, payout: 400 },
      { min: 11, max: 12, payout: 600 },
    ],
    bonusKey: 'shipping_normal_macro_overinvest_plus_200',
    bonusText: 'In a Normal Macro Regime, raise over-investment thresholds by +$200.',
  },
  {
    id: 'arms_manufacturing_contract',
    name: 'Arms Manufacturing Contract',
    class: 'Military',
    table: [
      { min: 2, max: 3, payout: 300 },
      { min: 4, max: 6, payout: 200 },
      { min: 7, max: 8, payout: 100 },
      { min: 9, max: 10, payout: -100 },
      { min: 11, max: 12, payout: -200 },
    ],
    bonusKey: 'arms_war_mobilization_plus_100',
    bonusText: '+$100 across outcomes if Macro is War Mobilization.',
  },
  {
    id: 'naval_shipyard_expansion',
    name: 'Naval Shipyard Expansion',
    class: 'Military',
    table: [
      { min: 2, max: 4, payout: -300 },
      { min: 5, max: 6, payout: -100 },
      { min: 7, max: 8, payout: 100 },
      { min: 9, max: 10, payout: 300 },
      { min: 11, max: 12, payout: 500 },
    ],
    bonusKey: 'naval_modifier_improves_plus_200',
    bonusText: 'If the Project Modifier results in a higher payout, +$200.',
  },
  {
    id: 'advanced_weapons_rd_program',
    name: 'Advanced Weapons R&D Program',
    class: 'Military',
    table: [
      { min: 2, max: 4, payout: -600 },
      { min: 5, max: 7, payout: -200 },
      { min: 8, max: 9, payout: 0 },
      { min: 10, max: 11, payout: 500 },
      { min: 12, max: 12, payout: 1000 },
    ],
    bonusKey: 'advanced_weapons_reroll_if_military_macro_low',
    bonusText: 'If Military Macro, roll again for just this project if adjusted roll is 7 or less.',
  },
];

export const MODIFIERS = [
  // Single project (4 each)
  {
    id: 'structural_advantage',
    name: 'Structural Advantage',
    type: 'Single',
    text: "If this project’s payout is positive, increase it by +$200.",
    copies: 4,
  },
  {
    id: 'demand_stability',
    name: 'Demand Stability',
    type: 'Single',
    text: "If this project’s payout is negative, improve it by +$200.",
    copies: 4,
  },
  {
    id: 'operational_fragility',
    name: 'Operational Fragility',
    type: 'Single',
    text: "If this project’s payout is negative, worsen it by -$200.",
    copies: 4,
  },
  {
    id: 'scale_inefficiency',
    name: 'Scale Inefficiency',
    type: 'Single',
    text: "If this project is over-invested, reduce any positive payout by -$200.",
    copies: 4,
  },
  // Cross-project (3 each except as shown)
  {
    id: 'monopoly_amplifier',
    name: 'Monopoly Amplifier',
    type: 'Cross',
    text: 'If this project has the highest positive payout: all other projects worsen by -$200. This project gains half of the total payout points removed (rounding down). (Ties: no effect.)',
    copies: 2,
  },
  {
    id: 'supply_chain_issues',
    name: 'Supply Chain Issues',
    type: 'Cross',
    text: 'This project gets -$300. If there are successful (positive) projects in the same macro group this round, those projects each get +$100 (rounding down).',
    copies: 2,
  },
  {
    id: 'cost_externalization',
    name: 'Cost Externalization',
    type: 'Cross',
    text: 'If this project resolves at -$100 or worse: this project +$200; all projects in the same macro group suffer -$200.',
    copies: 2,
  },
  {
    id: 'substitute_cannibalization',
    name: 'Substitute Cannibalization',
    type: 'Cross',
    text: 'If this project resolves positive and another project in the same macro group also resolves positive: reduce both by -$200.',
    copies: 2,
  },
  {
    id: 'breakthrough_discovery',
    name: 'Breakthrough Discovery',
    type: 'Cross',
    text: 'If this project resolves at +$400 or higher, increase its payout by +$300.',
    copies: 1,
  },
  {
    id: 'regulatory_backlash',
    name: 'Regulatory Backlash',
    type: 'Cross',
    text: 'If this project resolves at +$300 or higher, reduce its payout by -$300.',
    copies: 1,
  },
  {
    id: 'catastrophic_non_positive_payout',
    name: 'Catastrophic Non-positive payout',
    type: 'Extraordinary',
    text: 'If this project resolves at -$300 or worse, worsen it by -$300.',
    copies: 1,
  },
  {
    id: 'systemic_contagion',
    name: 'Systemic Contagion',
    type: 'Extraordinary',
    text: 'If this project resolves at -$300 or worse, all projects suffer -$200.',
    copies: 1,
  },
];

export const MACROS = [
  {
    id: 'innovation_boom',
    name: 'Innovation Boom',
    rollShiftByClass: { Growth: 2, Defensive: -1 },
    payoutWinner: { class: 'Growth', delta: 200 },
    payoutLoser: { class: 'Defensive', delta: -200 },
  },
  {
    id: 'commodity_spike',
    name: 'Commodity Spike',
    rollShiftByClass: { Normal: -2, Growth: 1 },
    payoutWinner: { class: 'Growth', delta: 200 },
    payoutLoser: { class: 'Normal', delta: -200 },
  },
  {
    id: 'public_safety_mandate',
    name: 'Public Safety Mandate',
    rollShiftByClass: { Defensive: 2, Growth: -2 },
    payoutWinner: { class: 'Defensive', delta: 200 },
    payoutLoser: { class: 'Growth', delta: -200 },
  },
  {
    id: 'geopolitical_standoff',
    name: 'Geopolitical Standoff',
    rollShiftByClass: { Defensive: 1, Military: -2 },
    payoutWinner: { class: 'Defensive', delta: 200 },
    payoutLoser: { class: 'Military', delta: -200 },
  },
  {
    id: 'consumer_expansion',
    name: 'Consumer Expansion',
    rollShiftByClass: { Normal: 2, Military: -1 },
    payoutWinner: { class: 'Normal', delta: 200 },
    payoutLoser: { class: 'Military', delta: -200 },
  },
  {
    id: 'regulatory_clampdown',
    name: 'Regulatory Clampdown',
    rollShiftByClass: { Normal: 1, Defensive: -2 },
    payoutWinner: { class: 'Normal', delta: 200 },
    payoutLoser: { class: 'Defensive', delta: -200 },
  },
  {
    id: 'war_mobilization',
    name: 'War Mobilization',
    rollShiftByClass: { Military: 2, Normal: -2 },
    payoutWinner: { class: 'Military', delta: 200 },
    payoutLoser: { class: 'Normal', delta: -200 },
  },
  {
    id: 'credit_crisis',
    name: 'Credit Crisis',
    // Non-Defensive -2; Defensive +1
    rollShiftByClass: { Defensive: 1, Normal: -2, Growth: -2, Military: -2 },
    payoutWinner: { class: 'Military', delta: 200 },
    payoutLoser: { class: 'Growth', delta: -200 },
  },
];
